### ISSUE TITLE
Add a button when you can put black and white mode icon have a moon same of this 🌔 

### ISSUE THREAD

**Issue by MarcoJ18** [MarcoJ18/reto1.github.io#1]

**Comment by abitsalihu** [comment]
Hey @MarcoJ18, I would like to help you with this issue. :)

**Comment by MarcoJ18** [comment]
@abitsalihu You can make a pull request if you want . And i try make a button when you press the button change the page to black mode i think is with js but i keep learning Web development. If you can help me i appreciative. Sorry with my english i very bad :)
